const ITEM_CATALOG_SOURCE = [
  {
    id: 'cordage',
    name: 'Cordage',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['cordage_material'],
  },
  {
    id: 'hide',
    name: 'Raw Hide',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['hide_material_raw'],
  },
  {
    id: 'dried_hide',
    name: 'Dried Hide',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['hide_material'],
  },
  {
    id: 'barkcloth',
    name: 'Barkcloth',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['barkcloth_material'],
  },
  {
    id: 'fat',
    name: 'Animal Fat',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    nutrition: {
      calories: 70,
      protein: 0,
      carbs: 0,
      fat: 13,
    },
  },
  {
    id: 'pole',
    name: 'Pole',
    category: 'intermediate',
    unit_weight_g: 1000,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['wood_pole'],
  },
  {
    id: 'branch',
    name: 'Branch',
    category: 'intermediate',
    unit_weight_g: 700,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['stiff_stick'],
  },
  {
    id: 'flint_cobble',
    name: 'Flint Cobble',
    category: 'intermediate',
    unit_weight_g: 500,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['flint_cobble'],
  },
  {
    id: 'flat_stone',
    name: 'Flat Stone',
    category: 'intermediate',
    unit_weight_g: 1200,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['flat_stone'],
  },
  {
    id: 'heavy_rock',
    name: 'Heavy Rock',
    category: 'intermediate',
    unit_weight_g: 4000,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['heavy_rock'],
  },
  {
    id: 'earthworm',
    name: 'Earthworm',
    category: 'intermediate',
    unit_weight_g: 1,
    decay_days: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['fish_bait'],
  },
];

export default ITEM_CATALOG_SOURCE;
