const ITEM_CATALOG_SOURCE = [
  {
    id: 'cordage',
    name: 'Cordage',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['cordage_material'],
  },
  {
    id: 'hide',
    name: 'Raw Hide',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['hide_material_raw'],
  },
  {
    id: 'dried_hide',
    name: 'Dried Hide',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['hide_material'],
  },
  {
    id: 'barkcloth',
    name: 'Barkcloth',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['barkcloth_material'],
  },
  {
    id: 'fat',
    name: 'Animal Fat',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    nutrition: {
      calories: 70,
      protein: 0,
      carbs: 0,
      fat: 13,
    },
  },
  {
    id: 'pole',
    name: 'Pole',
    category: 'intermediate',
    unit_weight_g: 1000,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['wood_pole'],
  },
  {
    id: 'pitch',
    name: 'Pitch',
    category: 'intermediate',
    unit_weight_g: 150,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['resin'],
  },
  {
    id: 'tree_sugar',
    name: 'Tree Sugar',
    category: 'food',
    // GDD §8.6: ~40:1 sap-to-sugar by volume; one output unit modeled as a small lump.
    unit_weight_g: 40,
    can_dry: false,
    can_freeze: true,
    field_edibility_score: 0.9,
    nutrition: {
      calories: 155,
      protein: 0,
      carbs: 40,
      fat: 0,
    },
  },
  {
    id: 'branch',
    name: 'Branch',
    category: 'intermediate',
    unit_weight_g: 700,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['stiff_stick'],
  },
  {
    id: 'flint_cobble',
    name: 'Flint Cobble',
    category: 'intermediate',
    unit_weight_g: 500,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['flint_cobble'],
  },
  {
    id: 'flat_stone',
    name: 'Flat Stone',
    category: 'intermediate',
    unit_weight_g: 1200,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['flat_stone'],
  },
  {
    id: 'heavy_rock',
    name: 'Heavy Rock',
    category: 'intermediate',
    unit_weight_g: 4000,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['heavy_rock'],
  },
  {
    id: 'earthworm',
    name: 'Earthworm',
    category: 'intermediate',
    unit_weight_g: 1,
    decay_days: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['fish_bait'],
  },
  {
    id: 'tool:stool',
    name: 'Stool',
    category: 'tool',
    unit_weight_g: 2200,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 2,
  },
  {
    id: 'tool:bone_hook',
    name: 'Bone Hook',
    category: 'tool',
    unit_weight_g: 30,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:auto_rod',
    name: 'Auto Rod',
    category: 'tool',
    unit_weight_g: 550,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:axe',
    name: 'Axe',
    category: 'tool',
    unit_weight_g: 1200,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:basket',
    name: 'Basket',
    category: 'tool',
    unit_weight_g: 800,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 2,
  },
  {
    id: 'tool:blickey',
    name: 'Blickey',
    category: 'tool',
    unit_weight_g: 300,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:carved_wooden_spout',
    name: 'Carved Wooden Spout',
    category: 'tool',
    unit_weight_g: 200,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:cordage_organizer',
    name: 'Cordage Organizer',
    category: 'tool',
    unit_weight_g: 250,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:dead_fall_trap',
    name: 'Deadfall Trap',
    category: 'tool',
    unit_weight_g: 2500,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:digging_stick',
    name: 'Digging Stick',
    category: 'tool',
    unit_weight_g: 400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:fish_trap_weir',
    name: 'Fish Trap / Weir',
    category: 'tool',
    unit_weight_g: 1800,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:fishing_rod',
    name: 'Fishing Rod',
    category: 'tool',
    unit_weight_g: 400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:flint_knife',
    name: 'Flint Knife',
    category: 'tool',
    unit_weight_g: 350,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:hide_pitch_vessel',
    name: 'Hide Pitch Vessel (Empty)',
    category: 'tool',
    // GDD craft: hide (800g) + pitch (×1) + 2 cordage units → approximate finished mass.
    unit_weight_g: 900,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:hide_pitch_vessel_filled_sap',
    name: 'Hide Pitch Vessel (Sap)',
    category: 'tool',
    // Empty vessel plus a full typical sap charge (~2L water-equivalent); approximate.
    unit_weight_g: 2900,
    can_dry: false,
    can_freeze: true,
    // Field "eat" drinks sap and returns empty vessel; tools default to 0 except this.
    field_edibility_score: 0.9,
  },
  {
    id: 'tool:hoe',
    name: 'Hoe',
    category: 'tool',
    unit_weight_g: 850,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:ladder',
    name: 'Ladder',
    category: 'tool',
    unit_weight_g: 4500,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 4,
  },
  {
    id: 'tool:marker_stick',
    name: 'Marker Stick',
    category: 'tool',
    unit_weight_g: 150,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:shovel',
    name: 'Shovel',
    category: 'tool',
    unit_weight_g: 900,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:simple_snare',
    name: 'Simple Snare',
    category: 'tool',
    unit_weight_g: 120,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:sled',
    name: 'Sled',
    category: 'tool',
    unit_weight_g: 3500,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 2,
  },
  {
    id: 'tool:wooden_platform',
    name: 'Wooden Platform',
    category: 'tool',
    unit_weight_g: 800,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin',
    name: 'Waterskin (Empty)',
    category: 'tool',
    unit_weight_g: 400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_safe_1',
    name: 'Waterskin (Safe Water, 1 Drink)',
    category: 'tool',
    unit_weight_g: 1400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_safe_2',
    name: 'Waterskin (Safe Water, 2 Drinks)',
    category: 'tool',
    unit_weight_g: 2400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_safe_3',
    name: 'Waterskin (Safe Water, 3 Drinks)',
    category: 'tool',
    unit_weight_g: 3400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_river_1',
    name: 'Waterskin (River Water, 1 Drink)',
    category: 'tool',
    unit_weight_g: 1400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_river_2',
    name: 'Waterskin (River Water, 2 Drinks)',
    category: 'tool',
    unit_weight_g: 2400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_river_3',
    name: 'Waterskin (River Water, 3 Drinks)',
    category: 'tool',
    unit_weight_g: 3400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_pond_1',
    name: 'Waterskin (Pond Water, 1 Drink)',
    category: 'tool',
    unit_weight_g: 1400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_pond_2',
    name: 'Waterskin (Pond Water, 2 Drinks)',
    category: 'tool',
    unit_weight_g: 2400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_pond_3',
    name: 'Waterskin (Pond Water, 3 Drinks)',
    category: 'tool',
    unit_weight_g: 3400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:gloves',
    name: 'Gloves',
    category: 'tool',
    unit_weight_g: 200,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:coat',
    name: 'Coat',
    category: 'tool',
    unit_weight_g: 1800,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:sun_hat',
    name: 'Sun Hat',
    category: 'tool',
    unit_weight_g: 250,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:leaching_basket',
    name: 'Leaching Basket',
    category: 'tool',
    unit_weight_g: 1200,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 2,
  },
];

export default ITEM_CATALOG_SOURCE;
