const ITEM_CATALOG_SOURCE = [
  {
    id: 'cordage',
    name: 'Cordage',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['cordage_material'],
  },
  {
    id: 'hide',
    name: 'Raw Hide',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['hide_material_raw'],
  },
  {
    id: 'dried_hide',
    name: 'Dried Hide',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['hide_material'],
  },
  {
    id: 'barkcloth',
    name: 'Barkcloth',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['barkcloth_material'],
  },
  {
    id: 'fat',
    name: 'Animal Fat',
    category: 'intermediate',
    unit_weight_g: 1,
    can_dry: false,
    can_freeze: true,
    nutrition: {
      calories: 70,
      protein: 0,
      carbs: 0,
      fat: 13,
    },
  },
  {
    id: 'pole',
    name: 'Pole',
    category: 'intermediate',
    unit_weight_g: 1000,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['wood_pole'],
  },
  {
    id: 'branch',
    name: 'Branch',
    category: 'intermediate',
    unit_weight_g: 700,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['stiff_stick'],
  },
  {
    id: 'flint_cobble',
    name: 'Flint Cobble',
    category: 'intermediate',
    unit_weight_g: 500,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['flint_cobble'],
  },
  {
    id: 'flat_stone',
    name: 'Flat Stone',
    category: 'intermediate',
    unit_weight_g: 1200,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['flat_stone'],
  },
  {
    id: 'heavy_rock',
    name: 'Heavy Rock',
    category: 'intermediate',
    unit_weight_g: 4000,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['heavy_rock'],
  },
  {
    id: 'earthworm',
    name: 'Earthworm',
    category: 'intermediate',
    unit_weight_g: 1,
    decay_days: 1,
    can_dry: false,
    can_freeze: true,
    craft_tags: ['fish_bait'],
  },
  {
    id: 'tool:stool',
    name: 'Stool',
    category: 'tool',
    unit_weight_g: 2200,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 2,
  },
  {
    id: 'tool:bone_hook',
    name: 'Bone Hook',
    category: 'tool',
    unit_weight_g: 30,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin',
    name: 'Waterskin (Empty)',
    category: 'tool',
    unit_weight_g: 400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_safe_1',
    name: 'Waterskin (Safe Water, 1 Drink)',
    category: 'tool',
    unit_weight_g: 1400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_safe_2',
    name: 'Waterskin (Safe Water, 2 Drinks)',
    category: 'tool',
    unit_weight_g: 2400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_safe_3',
    name: 'Waterskin (Safe Water, 3 Drinks)',
    category: 'tool',
    unit_weight_g: 3400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_river_1',
    name: 'Waterskin (River Water, 1 Drink)',
    category: 'tool',
    unit_weight_g: 1400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_river_2',
    name: 'Waterskin (River Water, 2 Drinks)',
    category: 'tool',
    unit_weight_g: 2400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_river_3',
    name: 'Waterskin (River Water, 3 Drinks)',
    category: 'tool',
    unit_weight_g: 3400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_pond_1',
    name: 'Waterskin (Pond Water, 1 Drink)',
    category: 'tool',
    unit_weight_g: 1400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_pond_2',
    name: 'Waterskin (Pond Water, 2 Drinks)',
    category: 'tool',
    unit_weight_g: 2400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:waterskin_pond_3',
    name: 'Waterskin (Pond Water, 3 Drinks)',
    category: 'tool',
    unit_weight_g: 3400,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:gloves',
    name: 'Gloves',
    category: 'tool',
    unit_weight_g: 200,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:coat',
    name: 'Coat',
    category: 'tool',
    unit_weight_g: 1800,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:sun_hat',
    name: 'Sun Hat',
    category: 'tool',
    unit_weight_g: 250,
    can_dry: false,
    can_freeze: true,
  },
  {
    id: 'tool:leaching_basket',
    name: 'Leaching Basket',
    category: 'tool',
    unit_weight_g: 1200,
    can_dry: false,
    can_freeze: true,
    footprintW: 2,
    footprintH: 2,
  },
];

export default ITEM_CATALOG_SOURCE;
